### ISSUE TITLE
Support for Homebridge 2.0

### ISSUE THREAD

**Issue by PappyChappy1** [valiquette/homebridge-rachio-irrigation#66]
Please update the plugin to work with Homebridge 2.0.  It breaks a lot of plugins once it goes live, and this is one of them.

**Comment by valiquette** [comment]
I do not have a controller to test against at this point just hose timers. Would you mind share the warning messages you see, and could you test a beta?

**Comment by PappyChappy1** [comment]
I could test a beta. This is the error below. The homebridge team has shared this link on how version 2.0 will break plugins:  TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare
> https://github.com/homebridge/homebridge
/wiki/Updating-To-Homebridge-v2.0

[7/23/2024, 10:35:17 PM] [Rachio] Error updating service TypeError: service.getCharacteristic(...).getValue is not a function
    at /opt/homebrew/lib/node_modules/homebridge-rachio-irrigation/rachioupdate.js:138:60
    at Array.forEach (<anonymous>)
    at RachioPlatform.updateService (/opt/homebrew/lib/node_modules/homebridge-rachio-irrigation/rachioupdate.js:133:38)
    at RachioPlatform.eventMsg (/opt/homebrew/lib/node_modules/homebridge-rachio-irrigation/rachioplatform.js:946:4)
    at RachioPlatform.setOnlineStatus (/opt/homebrew/lib/node_modules/homebridge-rachio-irrigation/rachioplatform.js:674:9)
    at /opt/homebrew/lib/node_modules/homebridge-rachio-irrigation/rachioplatform.js:454:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by valiquette** [comment]
I have posted a beta version that I tested against 2.0 beta 8 (which is no longer available) I was able to address the error you reported and a naming warning for valve accessories, I am not sure if the controller will have the same warning or not. 

If you can restart the plugin and look for errors and remove the cached accessory and restart.
thanks

**Comment by PappyChappy1** [comment]
This worked for me, thank you @valiquette
